version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:z
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run dev"
